#!/usr/bin/env bash
# This script install and configure haproxy.
# update system and install haproxy
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 4808-web-01 54.163.68.20:80 check
        server 4808-web-02 54.226.116.83:80 check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
